name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # Runs tests in parallel with matrix strategy https://docs.cypress.io/guides/guides/parallelization
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    # Also see warning here https://github.com/cypress-io/github-action#parallel
    # strategy:
    #   fail-fast: false # https://github.com/cypress-io/github-action/issues/48
    #   matrix:
    #     containers: [1, 2] # Uses 2 parallel instances

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Cy tests
        run: npx cypress run --spec "cypress/e2e/login.spec.js"

      # - name: Run Cypress tests
      #   uses: cypress-io/github-action@v6
      #   with:
      #     spec: cypress/e2e/firstTest.spec.js
      #     parallel: true
      #     record: true

        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          CYPRESS_USER_EMAIL: ${{ secrets.USER_EMAIL }}
          CYPRESS_USER_PASSWORD: ${{ secrets.USER_PASSWORD }}