name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:e2e

      - name: Archive test reports
        run: |
          mkdir -p artifacts
          zip -r artifacts/test-reports.zip cypress/results mochawesome-report mochawesome.json || true

      - name: Upload test reports artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: artifacts/test-reports.zip

        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          CYPRESS_USER_EMAIL: ${{ secrets.CYPRESS_USER_EMAIL }}
          CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}